name: 🍎 macOS
on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'gd3'

env:
  BASE_BRANCH: gd3
  SCONSFLAGS: platform=osx verbose=yes --jobs=4
  SCONS_CACHE_LIMIT: 4096

jobs:
  macos-editor:
    runs-on: "macos-latest"

    name: Editor (target=release_debug, tools=yes)

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Load .scons_cache directory
        id: macos-editor-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
           scons platform=osx tools=yes target=release_debug

      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: godot/bin/*

  macos-template:
    runs-on: "macos-latest"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Load .scons_cache directory
        id: macos-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
           scons platform=osx target=release tools=no
